# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 12:40
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190125_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='apellidos',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=account.models.avatar_upload),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='account',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter Username'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
